namespace PowerSDR
{
	public interface ICATCommands
	{
		CATParser Parser
		{
			set;
		}

		string AG(string s);
		string AI(string s);
		string BD();
		string BU();
		string DN();
		string FA(string s);
		string FB(string s);
		string FR(string s);
		string FT(string s);
		string FW(string s);
		string GT(string s);
		string ID();
		string IF();
		string KS(string s);
		string KY(string s);
		string MD(string s);
		string MG(string s);
		string MO(string s);
		string NB(string s);
		string NT(string s);
		string PC(string s);
		string PS(string s);
		string QI();
		string RC();
		string RD(string s);
		string RT(string s);
		string RU(string s);
		string RX(string s);
		string SH(string s);
		string SL(string s);
		string SM(string s);
		string SQ(string s);
		string TX(string s);
		string UP();
		string XT(string s);

		string ZZAG(string s);
		string ZZAI(string s);
		string ZZAR(string s);
		string ZZBD();
		string ZZBG(string s);
		string ZZBI(string s);
		string ZZBR(string s);
		string ZZBS(string s);
		string ZZBU();
		string ZZCB(string s);
		string ZZCD(string s);
		string ZZCF(string s);
		string ZZCI(string s);
		string ZZCL(string s);
		string ZZCM(string s);
		string ZZCP(string s);
		string ZZCS(string s);
		string ZZCT(string s);
		string ZZCU();
		string ZZDA(string s);
		string ZZDM(string s);
		string ZZDX(string s);
		string ZZEA(string s);
		string ZZEB(string s);
		string ZZER(string s);
		string ZZET(string s);
		string ZZFA(string s);
		string ZZFB(string s);
		string ZZFI(string s);
		string ZZFL(string s);
		string ZZFH(string s);
		string ZZFM();
		string ZZFV(string s);
		string ZZFW(string s);
		string ZZFX(string s);
		string ZZFY(string s);
		string ZZGE(string s);
		string ZZGL(string s);
		string ZZGT(string s);
		string ZZHA(string s);
		string ZZHR(string s);
		string ZZHT(string s);
		string ZZHU(string s);
		string ZZHV(string s);
		string ZZHW(string s);
		string ZZHX(string s);
		string ZZID();
		string ZZIF(string s);
		string ZZIS(string s);
		string ZZIT(string s);
		string ZZIU();
		string ZZKS(string s);
		string ZZKY(string s);
		string ZZMA(string s);
		string ZZMD(string s);
		string ZZMG(string s);
		string ZZMN(string s);
		string ZZMO(string s);
		string ZZMR(string s);
		string ZZMS(string s);
		string ZZMT(string s);
		string ZZMU(string s);
		string ZZNA(string s);
		string ZZNB(string s);
		string ZZNL(string s);
		string ZZNM(string s);
		string ZZNR(string s);
		string ZZNT(string s);
		string ZZOA(string s);
		string ZZOB(string s);
		string ZZOC(string s);
		string ZZOD(string s);
		string ZZOE(string s);
		string ZZOF(string s);
		string ZZOG(string s);
		string ZZOH(string s);
		string ZZOJ(string s);
		string ZZPA(string s);
		string ZZPC(string s);
		string ZZPD();
		string ZZPO(string s);
		string ZZPS(string s);
		string ZZPZ(string s);
		string ZZQM();
		string ZZQR();
		string ZZQS();
		string ZZRA(string s);
		string ZZRB(string s);
		string ZZRC();
		string ZZRD(string s);
		string ZZRF(string s);
		string ZZRH(string s);
		string ZZRL(string s);
		string ZZRM(string s);
		string ZZRS(string s);
		string ZZRT(string s);
		string ZZRU(string s);
		string ZZSA();
		string ZZSB();
		string ZZSD();
		string ZZSF(string s);
		string ZZSM(string s);
		string ZZSP(string s);
		string ZZSO(string s);
		string ZZSQ(string s);
		string ZZSR(string s);
		string ZZST();
		string ZZSU();
		string ZZTF(string s);
		string ZZTH(string s);
		string ZZTI(string s);
		string ZZTL(string s);
		string ZZTO(string s);
		string ZZTP(string s);
		string ZZTS();
		string ZZTU(string s);
		string ZZTX(string s);
		string ZZUA();
		string ZZVA(string s);
		string ZZVB(string s);
		string ZZVC(string s);
		string ZZVD(string s);
		string ZZVE(string s);
		string ZZVF(string s);
		string ZZVG(string s);
		string ZZVH(string s);
		string ZZVL(string s);
		string ZZVN();
		string ZZVS(string s);
		string ZZWA(string s);
		string ZZWB(string s);
		string ZZWC(string s);
		string ZZWD(string s);
		string ZZWE(string s);
		string ZZWF(string s);
		string ZZWG(string s);
		string ZZWH(string s);
		string ZZWJ(string s);
		string ZZWK(string s);
		string ZZWL(string s);
		string ZZWM(string s);
		string ZZWN(string s);
		string ZZWO(string s);
		string ZZWP(string s);
		string ZZWQ(string s);
		string ZZWR(string s);
		string ZZWS(string s);
		string ZZXC();
		string ZZXF(string s);
		string ZZXS(string s);
		string ZZXT(string s);
		string ZZZB();
		string ZZZZ();
	}	
}

